### ISSUE TITLE
Was the project abandoned?

### ISSUE THREAD

**Issue by edsonmedina** [sandeepcr529/codespy#6]
The screenshots looked very promising.

**Comment by sandeepcr529** [comment]
:) This feels good...

Yes, the project is abandoned. I had spend a lot of time and effort on this. But sadly the project received only lukewarm response from the forums I have posted this. Mostly [reddit](http://www.reddit.com/r/PHP/search?q=codespy).

**Comment by jkobus** [comment]
Its ugly but I like it.
